name: Upload SBOM

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch to build (e.g. main or release/1.2)'
        required: true
        default: 'master'
  push:
    tags:
      - v*

jobs:
  upload_sbom:
    if: ${{ github.repository == 'chaintope/tapyrus-faucet' }}
    name: Upload SBOM
    uses: chaintope/.github/.github/workflows/trivy-sbom.yml@main
    with:
      scan-target: "Gemfile.lock"
      ref: ${{ github.event.inputs.branch || github.ref_name }}
    secrets:
      dependencytrack-server: ${{ secrets.DEPENDENCYTRACK_SERVER }}
      dependencytrack-apikey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
      dependencytrack-project: ${{ secrets.DEPENDENCYTRACK_PROJECT }}